### ISSUE TITLE
[BUG] Performance Analyzer webserver on port 9600 not responding to any API calls

### ISSUE THREAD

**Issue by borutlukic** [opensearch-project/performance-analyzer-rca#545]
**What is the bug?**
Opensearch performance analyzer app throws exception on startup and is not working.

**How can one reproduce the bug?**
1. Run opensearch from docker image: opensearchproject/opensearch:2.12.0 expose port 9600
2. GET localhost:9600/_plugins/_performanceanalyzer/metrics
3. Hangs indefinitely (aka, no response is ever returned)

**What is the expected behavior?**
Expected is that the webserver API on port 9600 returns a response.

**What is your host/environment?**
 - OS: opensearchproject/opensearch:2.12.0 
 - Version 2.12.0
 - Plugins

**Do you have any additional context?**
See logs/PerformanceAnalyzer.log and notice:
```
Exception in thread "main" java.lang.IllegalArgumentException: cannot add context to list
        at jdk.httpserver/sun.net.httpserver.ContextList.add(ContextList.java:37)
        at jdk.httpserver/sun.net.httpserver.ServerImpl.createContext(ServerImpl.java:276)
        at jdk.httpserver/sun.net.httpserver.HttpServerImpl.createContext(HttpServerImpl.java:74)
        at jdk.httpserver/sun.net.httpserver.HttpServerImpl.createContext(HttpServerImpl.java:39)
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.createClientServers(PerformanceAnalyzerApp.java:354)
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.createClientServers(PerformanceAnalyzerApp.java:319)
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.main(PerformanceAnalyzerApp.java:112)
```
Checking the source code it is clear that the same handler is added twice, so the createContext functions throws an exception on the second attempt.
Code from PerformanceAnalyzerApp.java:
```
            httpServer.createContext(Util.METRICS_QUERY_URL, queryMetricsRequestHandler);
            httpServer.createContext(
                    Util.LEGACY_OPENDISTRO_METRICS_QUERY_URL, queryMetricsRequestHandler);
```
The Util.METRICS_QUERY_URL and Util.LEGACY_OPENDISTRO_METRICS_QUERY_URL are equal.

**Comment by tophercullen** [comment]
Ran into this issue. Tried 2.13. Same problem.

**Comment by borutlukic** [comment]
It is not a configuration issue. The code is broken. I think it started showing because JRE has been upgraded in 2.12 container. The old JRE had a bug in httpServer and it did not perform as per documentation so the above code worked. But in latest JRE they have fixed the issue, and adding same context twice will now throw exception on the second attempt. The 2 variables that define the context are hardcoded to same value in code and not configurable.

**Comment by ronnybremer** [comment]
same issue in OpenSearch 2.13, docker compose

**Comment by tophercullen** [comment]
@ronnybremer @borutlukic As remediation for [this JDK issue with opensearch](https://github.com/opensearch-project/OpenSearch/issues/12454), we downgraded the JDK version used in the docker image to 17. PA now appears to work....?

Example Dockerfile

`FROM  docker.io/opensearchproject/opensearch:2.12.0

USER 0
RUN --mount=type=cache,target=/var/cache/dnf,sharing=locked \
  dnf upgrade -y --refresh && dnf install -y java-17-amazon-corretto
USER 1000
ENV JAVA_HOME=/usr
`

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by kranthikirang** [comment]
This seems to be an issue in 2.16.0 as well. Any workarounds? or when can this fix is going to be available to OSS stream? Appreciate your help on this.

**Comment by rishabh6788** [comment]
Having the same exact issue, resolved by setting java to jdk-17.

**Comment by tobiasschweizer** [comment]
I am encountering the same issue with docker image 2.17 (opensearchproject/opensearch:2.17.0):

>  cat logs/PerformanceAnalyzer.log
Exception in thread "main" java.lang.IllegalArgumentException: cannot add context to list
        at jdk.httpserver/sun.net.httpserver.ContextList.add(ContextList.java:37)
        at jdk.httpserver/sun.net.httpserver.ServerImpl.createContext(ServerImpl.java:276)
        at jdk.httpserver/sun.net.httpserver.HttpServerImpl.createContext(HttpServerImpl.java:74)
        at jdk.httpserver/sun.net.httpserver.HttpServerImpl.createContext(HttpServerImpl.java:39)
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.createClientServers(PerformanceAnalyzerApp.java:354)
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.createClientServers(PerformanceAnalyzerApp.java:319)
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.main(PerformanceAnalyzerApp.java:112)

Any updates on this? Thanks for letting me know.

**Comment by taltsafrirpx** [comment]
do we have any update on this?
we have the same error in version 2.17

**Comment by Mr-Korben-Dallas** [comment]
Hello, same bug in 2.18

**Comment by tobiasschweizer** [comment]
Still there in 2.19. Does anyone know if https://github.com/opensearch-project/performance-analyzer-rca/pull/579 will be integrated?

**Comment by Mr-Korben-Dallas** [comment]
> Still there in 2.19. Does anyone know if [#579](https://github.com/opensearch-project/performance-analyzer-rca/pull/579) will be integrated?

Hi, I think they are not fixing the bug because a new version 3.0 is coming out soon in which "Performance-Analyzer-Rca: Will be replaced with the Telemetry plugin"

https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.19.0.md
